spring:
  application:
    name: Gateway-service
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://order-service:8081
          predicates:
            -  Path=/order/**
        - id: payment-service
          uri: http://payment-service:8082
          predicates:
            - Path=/payment/**
        - id: movie-service
          uri: http://movie-service:8083
          predicates:
            - Path=/api/**



server:
  port: 8085